---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: debian_role_postman_default
    image: debian
    hostname: debian_role_postman_default
    dockerfile: Dockerfile.j2
    pre_build_image: false
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
scenario:
  name: role.postman.default
  create_sequence:
    - create
  destroy_sequence:
    - destroy
  converge_sequence:
    - converge
  test_sequence:
    - lint
    - syntax
    - create
    - converge
    - idempotence
    - destroy
verifier:
  name: ansible
lint: |
  set -e
  yamllint roles/postman
  ansible-lint roles/postman
  flake8 roles/postman
