---
- name: Terraform | Molecule | Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Terraform | Molecule | Verify | Import Roles for variables
      ansible.builtin.import_role:
        name: arpanrec.nebula.terraform
        tasks_from: prerequisites

    - name: Terraform | Molecule | Get Release
      when: terraform_rv_version is not defined
      block:
        - name: Terrafrom | Molecule | Get Terraform Release from Github API
          ansible.builtin.uri:
            url: "https://api.github.com/repos/hashicorp/terraform/releases/latest"
            return_content: true
            status_code: 200
          register: terraform_rv_release_from_github

        - name: Terrafrom | Molecule | Set releases
          ansible.builtin.set_fact:
            terraform_rv_version: "{{ terraform_rv_release_from_github.json.tag_name[1:] }}"

    - name: Terraform | Molecule | Verify | Get terraform version from shell
      ansible.builtin.command: terraform --version
      environment:
        PATH: "{{ terraform_rv_install_path }}:{{ ansible_env.PATH }}"
      register: terraform_rv_version_shell_result
      changed_when: false

    - name: Terraform | Molecule | Verify | terraform version from shell result
      ansible.builtin.debug:
        var: terraform_rv_version_shell_result

    - name: Terraform | Molecule | Verify | Fail if terraform version is not present
      ansible.builtin.assert:
        that: terraform_rv_version_shell_result.stdout_lines[0] == "Terraform v{{ terraform_rv_version }}"
        success_msg: Terraform Version {{ terraform_rv_version }} is installed
        fail_msg: Terraform Version {{ terraform_rv_version }} is not installed, Shell result {{ terraform_rv_version_shell_result.stdout }}
