---
namespace: arpanrec
name: utilities
version: 4.1.2
readme: README.md
authors:
  - "Arpan Mandal <arpan.rec@gmail.com>"
description: common ansible resources
repository: https://github.com/arpanrec/ansible_collection_utilities.git
license_file: COPYING
# dependencies:
#   "https://github.com/ansible-collections/community.general.git": "6.0.1"
#   "https://github.com/ansible-collections/ansible.posix.git": "1.4.0"
#   "https://github.com/ansible-collections/community.docker.git": "3.3.1"
homepage: "https://arpanrec.com"
documentation: README.md
build_ignore:
  - ".github"
  - ".idea"
  - ".trunk"
  - ".vscode"
  - "venv"
  - "node_modules"
  - "molecule"
  - ".venv"
  - ".vscode"
tags:
  - "linux"
  - "debian"
