FROM "{{ item.image }}"

USER root

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y python3-venv git

RUN useradd -m -s /bin/bash -d /home/molecule-user molecule-user

WORKDIR /home/molecule-user

USER molecule-user
