---
- name: Postman | Unarchive the tarball
  ansible.builtin.unarchive:
    src: "{{ postman_rv_tarball_download_path }}"
    dest: "{{ postman_rv_install_path }}"
    extra_opts: [--strip-components=1]
    remote_src: true
