# trunk-ignore(hadolint/DL1000)
FROM "{{ item.image }}"

USER root

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y python3-venv \
    wget curl unzip

# For Icons
RUN apt-get install -y gtk-update-icon-cache

# For Icons
RUN apt-get install -y gnome-shell

RUN useradd -m -s /bin/bash -d /home/molecule-user molecule-user

WORKDIR /home/molecule-user

USER molecule-user
