---
- name: Bitwarden CLI | Molecule | Verify
  hosts: all
  gather_facts: true
  become: false
  tasks:
    - name: Bitwarden CLI | Molecule | Verify | Import Roles for variables
      ansible.builtin.include_vars:
        file: "../../roles/bw/defaults/main.yml"

    - name: Bitwarden CLI | Molecule | Verify | Get bw version from shell
      ansible.builtin.command: bw --version
      environment:
        PATH: "{{ bw_cli_rv_node_dependency_bin_dir }}:{{ ansible_env.PATH }}"
      register: bw_cli_rv_tmp_version_shell_result
      changed_when: false

    - name: Bitwarden CLI | Molecule | Verify | bw version from shell result
      ansible.builtin.debug:
        var: bw_cli_rv_tmp_version_shell_result

    - name: Bitwarden CLI | Molecule | Verify | Fail if bw version is not present
      ansible.builtin.assert:
        that: bw_cli_rv_tmp_version_shell_result.stdout ==  bw_cli_rv_version
        success_msg: BW Version {{ bw_cli_rv_version }} is installed
        fail_msg: BW Version {{ bw_cli_rv_version }} is not installed, Shell result {{ bw_cli_rv_tmp_version_shell_result.stdout }}
