---
- name: NodeJS | Molecule | Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: NodeJS | Molecule | Verify | Import Roles for variables
      ansible.builtin.import_role:
        name: arpanrec.utilities.nodejs
        tasks_from: prerequisites

    - name: NodeJS | Molecule | Verify | Get node version from shell
      ansible.builtin.command: node --version
      environment:
        PATH: "{{ nodejs_rv_install_path }}/bin:{{ ansible_env.PATH }}"
      register: nodejs_rv_version_shell_result
      changed_when: false

    - name: NodeJS | Molecule | Verify | nodejs version from shell result
      ansible.builtin.debug:
        var: nodejs_rv_version_shell_result

    - name: NodeJS | Molecule | Verify | Fail if nodejs version is not present
      ansible.builtin.assert:
        that: nodejs_rv_version_shell_result.stdout == "{{ nodejs_rv_version }}"
        success_msg: NodeJS Version {{ nodejs_rv_version }} is installed
        fail_msg: NodeJS Version {{ nodejs_rv_version }} is not installed, Shell result {{ nodejs_rv_version_shell_result.stdout }}
