---
- name: Themes | Fonts | Hack | Get latest releases
  ansible.builtin.uri:
    url: "https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest"
    method: GET
    return_content: true
    headers:
      Accept: "application/vnd.github.v3+json"
    status_code: 200
  register: pv_ua_fonts_github_latest_release

- name: Themes | Fonts | Hack | Get downloaded file stat
  ansible.builtin.stat:
    path: "{{ themes_rv_fonts_hack_download_path }}"
  register: pv_ua_fonts_tmp_downloaded_file_stat

- name: Themes | Fonts | Hack | Install
  when: not pv_ua_fonts_tmp_downloaded_file_stat.stat.exists
  block:
    - name: Themes | Fonts | Hack | Install | Download bin
      ansible.builtin.get_url:
        url: "{{ themes_rv_fonts_ryanoasis_nerd_fonts_download_url }}"
        dest: "{{ themes_rv_fonts_hack_download_path }}"
        mode: "0700"

    - name: Themes | Fonts | Hack | Install | Create Directory
      ansible.builtin.file:
        path: "{{ themes_rv_user_share_dir }}/fonts/hack"
        state: directory
        mode: "0700"

    - name: Themes | Fonts | Hack | Install | Copy to Fonts Directory
      ansible.builtin.unarchive:
        src: "{{ themes_rv_fonts_hack_download_path }}"
        dest: "{{ themes_rv_user_share_dir }}/fonts/hack"
        remote_src: true

    - name: Themes | Fonts | Hack | Install | Update font cache
      ansible.builtin.command: "fc-cache -f -v {{ themes_rv_user_share_dir }}/fonts/hack"
      register: pv_ua_fonts_hack_fonts_update_cache_result
      changed_when: true

    - name: Themes | Fonts | Hack | Install | Update Result
      ansible.builtin.debug:
        var: pv_ua_fonts_hack_fonts_update_cache_result
