---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: debian_role_vault_default
    hostname: debian_role_vault_default
    image: debian
    dockerfile: Dockerfile.j2
    pre_build_image: false
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
scenario:
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  create_sequence:
    - dependency
    - create
  test_sequence:
    - syntax
    - destroy
    - dependency
    - create
    - converge
    - verify
    - idempotence
    - destroy
verifier:
  name: ansible
