---
code_rv_tarball_download_path: "{{ code_rv_tmp_dir }}/vscode-{{ code_rv_version }}.linux.tar.gz"
code_rv_download_url_map:
  x86_64: "https://update.code.visualstudio.com/{{ code_rv_version }}/linux-x64/stable"
  aarch64: "https://update.code.visualstudio.com/{{ code_rv_version }}/linux-arm64/stable"
code_rv_xdg_icon_path: "{{ code_rv_xdg_icon_dir }}/code-userapps.desktop"
code_rv_xdg_uri_handler_path: "{{ code_rv_xdg_icon_dir }}/code-url-handler-userapps.desktop"
code_rv_user_config_dir: "{{ ansible_facts.user_dir }}/.config/Code/User"
